export const MESSAGE_TYPES = Object.freeze({
  // iframe → CMP
  IFRAME_READY: "IFRAME_READY",
  COMM_CHANGE_SUCCESS: "COMM_CHANGE_SUCCESS",
  COMM_CHANGE_ERROR: "COMM_CHANGE_ERROR",
  COMM_CHANGE_CANCEL: "COMM_CHANGE_CANCEL",

  // CMP → iframe
  INIT: "INIT",
});
