export const MOCK_PAN_RESPONSE = {
  success: true,
  response: [
    {
      customer: {
        customerId: "0000000000100291",
        firstName: "Ankit",
        middleName: null,
        lastName: "Sharma",
        address1: "12 MG Road",
        address2: "Connaught Place",
        address3: null,
        stateCode: "DL",
        cityCode: "New Delhi",
        pinCode: "110001",
        phone1: "9123456780",
        email: "ankit.sharma@gmail.com",
      },
      accounts: [
        {
          guarantorCustomerId1: "0000000000200001",
          guarantor1FirstName: "Vikas",
          guarantor1MiddleName: null,
          guarantor1LastName: "Gupta",
          guarantor1Address1: "45 Sector 18",
          guarantor1Address2: null,
          guarantor1Address3: null,
          guarantor1StateCode: "UP",
          guarantor1CityCode: "Noida",
          guarantor1PinCode: "201301",
          guarantor1Phone1: "9234567810",
          guarantor1Email: "vikas.gupta@gmail.com",
          guarantorCustomerId2: "0000000000200002",
          guarantor2FirstName: "Amit",
          guarantor2MiddleName: null,
          guarantor2LastName: "Verma",
          guarantor2Address1: "78 Raj Nagar",
          guarantor2Address2: null,
          guarantor2Address3: null,
          guarantor2StateCode: "UP",
          guarantor2CityCode: "Ghaziabad",
          guarantor2PinCode: "201002",
          guarantor2Phone1: "9345678120",
          guarantor2Email: "amit.verma@gmail.com",
          guarantorCustomerId3: "0000000000200003",
          guarantor3FirstName: "Rajeev",
          guarantor3MiddleName: null,
          guarantor3LastName: "Singh",
          guarantor3Address1: "22 DLF Phase 2",
          guarantor3Address2: null,
          guarantor3Address3: null,
          guarantor3StateCode: "HR",
          guarantor3CityCode: "Gurgaon",
          guarantor3PinCode: "122002",
          guarantor3Phone1: "9456781230",
          guarantor3Email: "rajeev.singh@gmail.com",
          guarantorCustomerId4: null,
        },
      ],
    },
  ],
  message: "Customer loan info fetched successfully",
};
